# Generated by Django 4.1.3 on 2023-08-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_text_comment_content_remove_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.PositiveIntegerField(default=1693247347),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.PositiveIntegerField(default=1693247347),
        ),
    ]
